server:
    port: 8085

services:
    catalog:
        url: http://localhost:8081
    user:
        url: http://localhost:8083

spring:
    application:
        name: order-service-worker
    
    datasource:
        url: jdbc:postgresql://localhost:5432/hekr_store_db?currentSchema=order-schema
        username: hekr_admin
        password: hekr_password
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                default-schema: order-schema
    
    flyway:
        enabled: true
        default-schema: order-schema
        create-schemas: true
        locations: classpath:db/migration
    
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener: 
            simple:
                prefetch: 10
                retry:
                    enabled: true
                    max-retries: 3

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics
    endpoint:
        health:
            show-details: always