server:
    port: 8082

spring:
    application:
        name: order-service
    
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener: 
            simple: 
                retry:
                    enabled: true
                    max-retries: 3

services:
    catalog:
        url: http://localhost:8081
    order-worker:
        url: http://localhost:8085
    user:
        url: http://localhost:8083
    warehouse:
        url: http://localhost:8084

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics
    endpoint:
        health:
            show-details: always