server:
    port: 8080

spring:
    application:
        name: order-service
    
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASS}
        listener: 
            simple: 
                retry:
                    enabled: true
                    max-retries: 3

services:
    catalog:
        url: http://catalog-service:8080
    order-worker:
        url: http://order-service-worker:8080
    user:
        url: http://user-service:8080
    warehouse:
        url: http://warehouse-service:8080

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics
    endpoint:
        health:
            show-details: always