CREATE TABLE warehouses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address text NOT NULL
);

CREATE TABLE stock (
    variant_id bigint NOT NULL,
    warehouse_id bigint NOT NULL REFERENCES warehouses(id),
    quantity bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (variant_id, warehouse_id)
);
