CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(32) UNIQUE NOT NULL,
    password_hash text NOT NULL,
    role varchar(32) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_approved boolean NOT NULL DEFAULT false,
    client_type varchar(32) NOT NULL,
    phone varchar(20) NOT NULL,
    email varchar(256) NOT NULL
);

CREATE TABLE individual_details (
    user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    first_name varchar(256) NOT NULL,
    last_name varchar(256) NOT NULL,
    midname varchar(256),
    birthdate date NOT NULL,
    passport_series varchar(4) NOT NULL,
    passport_number varchar(6) NOT NULL
);

CREATE TABLE legal_details (
    user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    company_name varchar(256) NOT NULL,
    inn varchar(12) NOT NULL,
    kpp varchar(9),
    ogrn varchar(15) NOT NULL,
    legal_address varchar(256) NOT NULL
);

CREATE TABLE user_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expiry_date timestamp without time zone NOT NULL,
    revoked boolean NOT NULL DEFAULT false
);

CREATE INDEX idx_user_tokens_user_id ON user_tokens(user_id);
