server:
    port: 8080

gateway:
    routes:
        - path: "/api/v1/catalog/**"
          uri: "http://catalog-service:8080"
        - path: "/api/v1/cart/**"
          uri: "http://catalog-service:8080"
        - path: "/api/v1/order/**"
          uri: "http://order-service:8080"
        - path: "/api/v1/user/**"
          uri: "http://user-service:8080"
        - path: "/api/v1/warehouse/**"
          uri: "http://warehouse-service:8080"
        - path: "/api/v1/stock/**"
          uri: "http://warehouse-service:8080"

jwt:
    secret: "${JWT_SECRET}"
    expiration: "${JWT_EXPIRATION:3600000}"
    refresh-token:
        expiration:  "${JWT_REFRESH_TOKEN_EXPIRATION:604800000}"
spring:
    application:
        name: api-gateway
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
    
management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics
    endpoint:
        health:
            show-details: always